### ISSUE TITLE
Save voting history for select proposals (eg. motions)

### ISSUE THREAD

**Issue by FloorLamp** [ic-rocks/ic-rocks#19]
We should save votes for proposals of type `Motion` to give more insight into governance participation.

**Comment by wpb1** [comment]
When it comes to roadmap proposals, there would be a lot of potential value in recording the total votes prior to liquid democracy.  For example, on the BTC integration proposal the manual vote was something like 14M  accept and 10M reject, but after DF voted it was 305M accept and 10M reject.  Those results tell very different stories.  DF has agreed to cast their votes with the majority after a specified manual voting period.  

In fact, it may be a good idea to make a proposal leaderboard into a dominate page on ic rocks when certain roadmap proposals are in progress.

**Comment by tarek-eg** [comment]
I would like to work on this issue next, any ideas?
For example how do we differentiate between individual votes vs Dfinity with their followers vote?

**Comment by wpb1** [comment]
Create a vote history chart with two trends...accept and decline.  Update every 1 minute (or every 5 minutes).  When DF and ICA vote, one of the trends will suddenly jump to somewhere around 316M total votes cast (the previous vote is a good proxy for how much total voting power exists).  Once the proposal receives 51% of total
voting power in either accept or reject category, the vote is over.  The total manual vote is how many votes were cast in the minutes before this sudden jump.

**Comment by tarek-eg** [comment]
@wpb1 That sounds good

So from a database point of view we will have to run a process that query voting state on an interval i.e each 1 hour, store it somewhere along with it's timestamp

I can imagine it would look like this: 
| timestamp | Yes | No |
| ------------ | ------------ | ------------ | 
|  21.10.2021 9 AM|  10k | 1k | 
|  21.10.2021 10 AM|  20k | 2k | 
|  21.10.2021 11 AM|  300M | 2k | 

1. Query current voting state.
2. if result is the same as last result => do nothing.
3. if result is different => store it.
4. do that until proposal is finished

That doesn't mark a certain percentage if it comes from individuals or not but it gives a history and it would be obvious when DF has voted.

The second question is where to display this data, my suggestion is to display it under the individual [proposal page](https://ic.rocks/proposal/20586) (under the details) as a vote overtime chart same as [this one](https://ic.rocks/charts/subnets) with two trend lines of yes and no

**Comment by wpb1** [comment]
@tarek-eg That sounds like a great plan.  I think you should save data more frequently than 1 hour.  The vote can change a lot in a short timeframe, so I wouldn't save less frequently than 5 minutes.  I like how you are planning to not save data that hasn't changed.  For your trend chart, I recommend scaling the y-axis to match the previous votes cast plus 5%.  Also, the language used in the NNS app is Adopt and Reject, so it seems reasonable to use that in ic rocks too.  I'm looking forward to trying this out at the next roadmap proposal.

**Comment by FloorLamp** [comment]
It looks like we're currently saving `no` ballots here, can be tweaked slightly: https://github.com/ic-rocks/api/blob/main/etl/neuron.ts#L171

**Comment by wpb1** [comment]
I'm not sure if this belongs here or a new issue, but we should consider displaying details of a proposal on ic rocks in a way that is easy to understand and follow for non-dev people.  I know the GitHub is linked for each proposal in the NNS app, but GitHub is not intuitive to normal people.  This idea only makes sense if the information can be queried from GitHub and displayed on ic rocks automatically.  It would also be useful for roadmap proposals if we can somehow link the forum discussions for that proposal.  In other words, create a well organized, easy to use interface for people to go when they want to review proposals as they prepare to vote and want to study vote history.

**Comment by tarek-eg** [comment]
The proposal section definitely needs improvement, I like how the [ICA displays the proposals](https://dashboard.internetcomputer.org/proposal/21340) I would say we could at least copy the same but maybe we can discuss that in a different issue.
