### ISSUE TITLE
Saving voting_power instead of calculating

### ISSUE THREAD

**Issue by FloorLamp** [ic-rocks/ic-rocks#24]
Currently, we [calculate](https://github.com/ic-rocks/api/blob/main/routes/neurons.ts/#L202-L207) each neuron's voting power, instead of saving the returned value from the [governance canister](https://github.com/ic-rocks/api/blob/main/etl/neuron.ts#L90). The entity column will need to be [created](https://github.com/ic-rocks/api/blob/main/entity/Neuron.ts#L82)

**Comment by tarek-eg** [comment]
@wpb1 mentioned he wants to prioritize this issue first, so I will look in to this one

**Comment by tarek-eg** [comment]
If the governance canister exposes the voting power what was the motive to calculate it instead?
